name: Go
on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
    paths:
      - '**.go'
      - 'go.mod'
      - '.golangci.yml'
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '.golangci.yml'
      - '.github/workflows/go.yml'
env:
  GOPROXY: "https://proxy.golang.org"

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [ 1.22.x ]
        platform: [ ubuntu-latest ] # macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd server 
          go test -v -race ./...
      
  # Running tests with race detection consumes too much memory on Windows,
  # see https://github.com/golang/go/issues/46099 for details.
  test-windows:
    name: TestOnWindows
    strategy:
      matrix:
        go-version: [ 1.22.x ]
        platform: [ windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd server 
          go test -v ./...
